### ISSUE TITLE
Speak and AI behind speak not functioning?

### ISSUE THREAD

**Issue by erilyth** [walterbender/speak#6]
Is it just me or anyone else facing the issue that text to Speech is not working, and on entering text and pressing enter or the 'Go' button next to the text does not start a text-to-speech dialogue. The mode where we talk with the bot is also not working. Entering text and pressing enter etc, do not trigger the robot and I get no response.
I don't get any errors in the log either.

**Comment by walterbender** [comment]
Works for me. Can you describe what your set up is?

**Comment by erilyth** [comment]
I was testing with Ubuntu 14.04 and the sugar build environment (from the sugar repo) and it was not working. However it works fine on Fedora 23 with the same setup. I also tested with the Sugar On a Stick and it seemed to work fine. I think there is something wrong in the way I set up my dev environment on Ubuntu, Ill try find out why its happening.
